### ISSUE TITLE
Double click action sometimes triggered twice

### ISSUE THREAD

**Issue by vsennedot** [eclipse-nattable/nattable#102]
If you configure the edit bindings to register the `MouseEditAction` on a double click instead of a single click and that the editor is a dialog which opens an SWT `Browser` with the `SWT.EDGE` style, the editor will be opened twice.

When double clicking on the cell, the `MouseUp` event then the `MouseDoubleClick` event are sent. But during the creation of the Edge browser, the `Display.readAndDispatch()` method is called, which send a second `MouseUp` event and is considered as mouse double click by the `MouseModeEventHandler`.

Checking if `doubleClick` is still false before calling `mouseDoubleClick(event);` in the `mouseUp()` method seems to fix that.

**Comment by fipro78** [comment]
Some questions before I am able to have a look:

- which version of NatTable?
- which Eclipse / SWT version?
- can you provide a simple reproducer, maybe based on one of the examples?

The `doubleClick` flag is used to handle exclusive single click actions. So I am not sure if an additional check would solve your problem or lead to an effect that other scenarios do not work anymore.

So I would like to investigate in detail to see why there is another mouse up event where there shouldn't be one.

**Comment by vsennedot** [comment]
NatTable 2.4.0
Eclipse / SWT from the 2024-06 repository

I was able to reproduce it by editing the example `EditorExample`:
I created a `new Browser(parent, SWT.EDGE);` in the `MultiLineTextCellEditor` and changed the `DefaultEditBindings` to use `registerDoubleClickBinding` instead of `registerSingleClickBinding` for the `MouseEditAction`.

```
        configRegistry.registerConfigAttribute(
                EditConfigAttributes.CELL_EDITOR,
                new MultiLineTextCellEditor(false) {

                    @Override
                    public Text createEditorControl(Composite parent) {
                        new Browser(parent, SWT.EDGE);
                        return super.createEditorControl(parent);
                    }
                },
                DisplayMode.NORMAL,
                EditorExample.COLUMN_FOUR_LABEL);
```
