### ISSUE TITLE
DataLayer.getColumnWidthByPosition() != DataLayer.setColumnWidthByPosition()

### ISSUE THREAD

**Issue by thomasa299792** [eclipse-nattable/nattable#115]
User had display zoom at 200 percent. When user changed the set of columns displayed, I used `DataLayer.getColumnWidthByPosition()` to remember the old widths, and reset them at the columns' new positions with `DataLayer.setColumnWidthByPosition()`. The columns got smaller and smaller each time. 

Eventually traced down the user's issue to `SizeConfig.getSize()` and `SizeConfig.setSize()`. I assumed from their names that they'd operate on the same value. But the former scales, and the latter does not. 

I don't have an idea whether this can be addressed with the existing methods without breaking other software. But at least it would be nice to offer:

* Method documentation of the inconsistent behavior.
* New accessor that provides the size unscaled.

Observed in 2.0.5, but appears to be the same issue in 2.4.0.

**Comment by fipro78** [comment]
The scaling topic is a long and complicated one. And it took a while to get it working in a backwards compatible way. So to answer your first question, no it is not possible to address this in an API consistent way as you would like it.

Regarding the documentation, well yes, that could be improved. Feel free to create a PR.

There are accessor methods that provide the size unscaled, e.g. `DataLayer#getConfiguredColumnWidthByPosition(int)`

And regarding your use case, there is already support to reset the size configuration, either via `DataLayer#resetColumnWidth(int, boolean)` or more globally by executing a `ColumnWidthResetCommand`

This is mentioned in the [NatTable 1.6.0 New & Noteworthy](https://eclipse.dev/nattable/nandn/nandn_160.php)
