### ISSUE TITLE
Feature Request: Row Hover

### ISSUE THREAD

**Issue by JR-1993** [eclipse-nattable/nattable#131]
As a user of the NatTable, I want to be able to see the related data of a row faster.

**Conversation:**
As companion piece to the RowSelection a row hover would be nice.
It is a feature that increases the usability of the table.

**Criteria**
- Being able to style the hover
- Being able to combine row and cell hover (style of hovered cell can be different from rest of row hover)
- There is a new example for implementing a row hover in the examples project

**Comment by fipro78** [comment]
The main issue is that the hover feature only fires CellVisualUpdateEvents, which is for performance reasons, to not render the whole visible table when hovering over a single cell.

If the whole row or the whole column should be repainted, the respective RowVisualUpdateEvent or ColumnVisualUpdateEvent need to be fired.

I extended the `HoverLayer` to be able to configure the type of visual change event that should be fired. I also added methods to ask if a cell in a row or a column is currently hovered. This allows to add label accumulators that inspect the `HoverLayer` to be able to add additional labels to other row cells, if a cell in that row is hovered for example.

I added the `_5066_GridBodyAxisHoverStylingExample` to show how the different configurations could look like. It also shows how you could achieve that the column/row header cells on a hovered cell in the body could update.
