### ISSUE TITLE
Change Request: scaling factor when zooming (zooming in smaller steps)

### ISSUE THREAD

**Issue by JR-1993** [eclipse-nattable/nattable#132]
As a user I want to be able to customize the size of a table better.

**Conversation**
The steps between the new zoom are too large.
I don't know what a good factor for zooming is.
IMO 10% steps like in Firefox feel good.

The factor for scaling right now is (found in ScalingUtils.java):
- 288 / 192 = 1,5
- 192 / 144 = 1,3333
- 144 / 120 = 1,2
- 120 / 96 = 1,25
- Below that a factor of 2.

**Criteria**
- Zooming the NatTable is done in smaller steps like 10%
- Icons and font still scale pixelfree

**Comment by fipro78** [comment]
The reason for the scaling as it is, is related to the possible scaling options in the OS. The default icons in NatTable are available for those scaling factors. If there is no icon for the scaling factor available, it will scale the existing image programmatically using `ImageData#scaledTo()`. The result typically doesn't look good, as we are talking about pixel images, and not SVG images.

While for fonts and the table itself it would work, the criteria "Icons and font still scale pixelfree" will never match for the images/icons part.

**Comment by fipro78** [comment]
As mentioned the scaling in smaller steps can have a negative impact on images. So I decided to add an option to enable the scaling in smaller steps. The default stays as it is.

To enable the smaller steps, you need to add the `ScalingUiBindingConfiguration` like this:

```java
natTable.addConfiguration(new ScalingUiBindingConfiguration(natTable, true));
```

The percentage configuration will increase/decrease generally by 10%, and will use one of the predefined OS scalings in case the calculated DPI are "near" the OS scaling value.
