### ISSUE TITLE
nattable example application shows only empty pages under windows

### ISSUE THREAD

**Issue by Veroni23** [eclipse-nattable/nattable#89]
Summary
The nattable example client shows empty pages for all of the elements in the navigation.

Steps to reproduce
Downloaded the nattable examples for windows from this page:
https://eclipse.dev/nattable/documentation.php?page=examples_application
Extract the zip. In the resulting folder, double-click nattable_examples.exe.
I am running Windows 11 Enterprise 22H2.

What is the current bug behavior?
Two directories are created (configuration and workspace) and a UI appears.
It has a navigation tree where items can be expanded and collapsed. When clicking on any of the examples (tree items), the page on the right stays empty.

![2024-05-29 16_56_27-org eclipse nebula widgets nattable examples e4 product-win32 win32 x86_64](https://github.com/eclipse-nattable/nattable/assets/31304981/d3bd9e5c-d1a5-4486-98f1-82f966296cd3)

What is the expected correct behavior?
It is expected to see the nattable examples in the page on the right - as shown in the screenshot on the documentation page.

**Comment by fipro78** [comment]
Just tested on my Windows 11 laptop and it works as intended.

The error you describe typically means that an exception happens in the background that is not reported back to the UI. Please have a look in the folder _workspace/.metadata_ and check if there is a _.log_ file. If there is such a file, it should give you an indication what the issue is.

**Comment by Veroni23** [comment]
I checked there already and there is no logging at all. Do you think there is any other location around my system where the logging might have gone to, or could you provide me with a log config (and where to put it) to get the logging output?

(As a sidenote: I have started it in a location on my system that is in the virus scanner's ignore list, so I am sure that no files have been deleted.)

**Comment by fipro78** [comment]
You could try to start the application from the console. Maybe the logging is written there.

**Comment by Veroni23** [comment]
Unfortunately, no logging is written to the console either.

**Comment by fipro78** [comment]
IIRC the examples App contains the simple binding that should write logs to the console.

You could try to to start the examples from the jar. Maybe that reveals the issue.

Which Java version do you use?

**Comment by Veroni23** [comment]
$ java --version
openjdk 11.0.19 2023-04-18
OpenJDK Runtime Environment Temurin-11.0.19+7 (build 11.0.19+7)
OpenJDK 64-Bit Server VM Temurin-11.0.19+7 (build 11.0.19+7, mixed mode)

I have just tried to use Java 17 by adding --jvm C:\Program Files\Eclipse Adoptium\jdk-17.0.7+7\bin to the nattable_example.ini, but the result is the same...

**Comment by fipro78** [comment]
You can try to start the application with a console. From the commandline this would be 

```
nattable_examples.exe -console
```

Maybe this prints out the issue.

**Comment by Veroni23** [comment]
Still the same... the console is opened but nothing is ever printed there. The program shows the same behavior.

**Comment by Veroni23** [comment]
You can close the ticket. 

As described in the ticket, this is what I did: "When clicking on any of the examples (tree items), the page on the right stays empty."

And I meant "clicking". I just found out by accident that you need to _double_ click to open any of the examples after spending hours of trying to get the logging to work, exchanging jdks, etc... :(

**Comment by fipro78** [comment]
I suppose you typically use VS Code and therefore expect views to open on a single click?

In Eclipse views and editors open on double clicks. And the example application is based on Eclipse and the UX that is common there. So I haven't thought about that anybody would expect the examples to open on a single click.

Sorry for not seeing that detail in your ticket.

**Comment by Veroni23** [comment]
I actually do use Eclipse, but it still did not occur to me... 

Most modern applications don't use you double-click any more because it is less accessible especially for new users of an application, and there is no visual cue when to click or when to double-click. 

Eclipse unfortunately is still in the last decade when it comes to usability. Its defaults often make it hard to design applications with great usability.

This is of course out of scope of this issue. :)
Thanks for getting back to me so fast and holding my hand while I figured it out.
