### ISSUE TITLE
DimensionallyDependentLayer.getDataValueByPosition() does not check for failed coord conversion, leading to exception

### ISSUE THREAD

**Issue by thomasa299792** [eclipse-nattable/nattable#93]
The method `DimensionallyDependentLayer.getDataValueByPosition()` does not check the return values of the calls to `LayerUtil.convertColumnPosition()` and `LayerUtil.convertRowPosition()`. 

Consequently, it can pass -1 for one or both coordinates to `this.baseLayer.getDataValueByPosition()`, which leads to an exception. 

Observed in 2.0.5, but see the same code in 2.4.0.

Current code:
```
    @Override
    public Object getDataValueByPosition(int columnPosition, int rowPosition) {
        int baseColumnPosition = LayerUtil.convertColumnPosition(this, columnPosition, this.baseLayer);
        int baseRowPosition = LayerUtil.convertRowPosition(this, rowPosition, this.baseLayer);
        return this.baseLayer.getDataValueByPosition(baseColumnPosition, baseRowPosition);
    }
```

One possible fix:
```
	    public Object getDataValueByPosition(int columnPosition, int rowPosition) {
                int baseColumnPosition = LayerUtil.convertColumnPosition(this, columnPosition, this.baseLayer);
                int baseRowPosition = LayerUtil.convertRowPosition(this, rowPosition, this.baseLayer);
	        
	        return ( (baseColumnPosition < 0) || (baseRowPosition < 0))
	        	? null
	        	: this.baseLayer.getDataValueByPosition(baseColumnPosition, baseRowPosition);
	    }
```

**Comment by fipro78** [comment]
Do you have an example when this happens? I agree from just looking at the code. But it did never occur before. And if it did, it revealed an issue with the composition.

**Comment by fipro78** [comment]
@thomasa299792 
I double checked this and noticed that there is never such a check in any layer. So I really wonder when you got an exception caused by this. My assumption is that you used something in the wrong way, which lead to the exception, and I would like to understand this better, before I simply add a check that might hide a usage issue.

**Comment by fipro78** [comment]
I am closing this issue now. 
- There is no response on my questions.
- There is never a check in any layer in `getDataValueByPosition()`
- IIRC the issue can only happen if the API is used in a way that will not work. Typically the wrong layers are used to do some custom operations. In the past I argumented that a handling like the suggested would hide the usage issue.
